### ISSUE TITLE
Manually close the lightbox

### ISSUE THREAD

**Issue by markmandel** [buckwilson/Lightbox_me#4]
It would be very useful if closeLightbox() was made public, so that if you needed to close the lightbox through some elements that were not initially exposed - either because the DOM element didn't exist when the lightbox was created, or was generated through an AJAX request, it could be done with a simple function call.

**Comment by buckwilson** [comment]
As of now, you can't generate the lightbox without passing it a DOM element. The only way this would be useful is if somehow the DOM element was removed before closing the lightbox. Or am I not understanding what you're saying?

I wouldn't mind adding a public function but I specifically designed it (or tried to, at least) so that you could invoke multiple lightboxes if you wanted, and close each of them independently. A public function would have to be written to close all overlays and hide all elements lightboxed by the plugin.

**Comment by markmandel** [comment]
To explain (possibly a little better), I have a lightbox "loader" image which displays, while I am loading a larger image in the background.

I then do something akin to:
$("#image_holder").children().replace(this);

Suddenly, the elements that have the click binding attached to them, are no longer there.

**Comment by ryangiglio** [comment]
Mark, I've been having this problem and found a way to work around it. If you bind the click element to something that isn't going to be replaced (outside image_holder), you can add a new click button like this

```
$('#newCloseButton').click(function(){
    $('#hiddenCloseElement').trigger('click');
});
```

**Comment by markmandel** [comment]
Thanks @ryangiglio, I don't have the code in front of me, but I solved it by faking an 'ESC' key press, that also did the trick.

**Comment by i-like-robots** [comment]
I bound my own event. The modal displays an iframe for an image upload. When the upload is complete it calls a custom event, simple enough:

$(window).bind('image-loaded', function() { closeLightbox(); return false; });

Which can be called like so:

$(window).trigger("image-loaded");

**Comment by buckwilson** [comment]
Mark: the new version of lightbox_me will allow you to invoke .lightbox_me() on a different element while the loader is still going, without consequence. This should solve all your binding issues, as they re-bind when you invoke .lightbox_me the second time.
